DROP TABLE IF EXISTS `T_DRUNKED_LOG`;
CREATE TABLE `T_DRUNKED_LOG` (
  `LOG_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'ログ日時',
  `LOG_PLACE` VARCHAR(100) NOT NULL COMMENT '計測場所',
  `DRUNKED_WEIGHT` smallint NOT NULL COMMENT '飲水量',
  PRIMARY KEY (`LOG_DATETIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='飲水量ログ'